
version: "3"

services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    container_name: next
    restart: always
    volumes:
      - ./next:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: banking
      MYSQL_PORT: 3306
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
